name: Node.js CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm i
    - run: pnpm lint
    - run: pnpm test:ci

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/v') && github.repository_owner == 'vuetifyjs'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - run: pnpm i
    - run: npm config set //registry.npmjs.org/:_authToken ${NPM_API_KEY:?}
      env:
        NPM_API_KEY: ${{ secrets.NPM_TOKEN }}
    - run: npm publish
    - name: GitHub release
      run: pnpm conventional-github-releaser -p vuetify
      env:
        CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
